import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css"
import Header from "@/ui/header/HeaderUi";
import Footer from "@/ui/footer/FooterUI";

const geistSans = Geist({
  weight:['100','200','300','400','500','600','700','800','900'],
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  weight:['100','200','300','400','500','600','700','800','900'],
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
    
        <Header/>
        {children}
        <Footer/>
      
      </body>
    </html>
  );
}
